<a href="https://colab.research.google.com/github/YonggunJung/ICT_TensorFlow/blob/main/Lotto1087%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto.csv')
df

1   2   3   4   5   6     일     이     삼     사     오     육
0      4   7  17  18  38  44   8.0  12.0  13.0  29.0  33.0  42.0
1      8  12  13  29  33  42   3.0   7.0  14.0  15.0  22.0  38.0
2      3   7  14  15  22  38  21.0  26.0  27.0  32.0  34.0  42.0
3     21  26  27  32  34  42   1.0   9.0  16.0  23.0  24.0  38.0
4      1   9  16  23  24  38  13.0  16.0  23.0  31.0  36.0  44.0
...   ..  ..  ..  ..  ..  ..   ...   ...   ...   ...   ...   ...
1081  14  27  30  31  40  42  11.0  16.0  19.0  21.0  27.0  31.0
1082  11  16  19  21  27  31   9.0  13.0  21.0  25.0  32.0  42.0
1083   9  13  21  25  32  42  10.0  23.0  29.0  33.0  37.0  40.0
1084  10  23  29  33  37  40  11.0  16.0  25.0  27.0  35.0  36.0
1085  11  16  25  27  35  36   NaN   NaN   NaN   NaN   NaN   NaN

[1086 rows x 12 columns]

In [ ]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1081  14  27  30  31  40  42
1082  11  16  19  21  27  31
1083   9  13  21  25  32  42
1084  10  23  29  33  37  40
1085  11  16  25  27  35  36

[1086 rows x 6 columns]

In [ ]:
Xtest = Xtrain.loc[1085]
Xtest

1    11
2    16
3    25
4    27
5    35
6    36
Name: 1085, dtype: int64

In [ ]:
Xtrain.drop(1085, inplace = True)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1080  16  24  29  40  41  42
1081  14  27  30  31  40  42
1082  11  16  19  21  27  31
1083   9  13  21  25  32  42
1084  10  23  29  33  37  40

[1085 rows x 6 columns]

In [ ]:
ytrain = df.drop(['1', '2', '3', '4','5', '6'], axis = 1)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1081  11.0  16.0  19.0  21.0  27.0  31.0
1082   9.0  13.0  21.0  25.0  32.0  42.0
1083  10.0  23.0  29.0  33.0  37.0  40.0
1084  11.0  16.0  25.0  27.0  35.0  36.0
1085   NaN   NaN   NaN   NaN   NaN   NaN

[1086 rows x 6 columns]

In [ ]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1080  14.0  27.0  30.0  31.0  40.0  42.0
1081  11.0  16.0  19.0  21.0  27.0  31.0
1082   9.0  13.0  21.0  25.0  32.0  42.0
1083  10.0  23.0  29.0  33.0  37.0  40.0
1084  11.0  16.0  25.0  27.0  35.0  36.0

[1085 rows x 6 columns]

In [ ]:
ytrain =ytrain.astype(int)
ytrain

일   이   삼   사   오   육
0      8  12  13  29  33  42
1      3   7  14  15  22  38
2     21  26  27  32  34  42
3      1   9  16  23  24  38
4     13  16  23  31  36  44
...   ..  ..  ..  ..  ..  ..
1080  14  27  30  31  40  42
1081  11  16  19  21  27  31
1082   9  13  21  25  32  42
1083  10  23  29  33  37  40
1084  11  16  25  27  35  36

[1085 rows x 6 columns]

In [ ]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

11  16  25  27  35  36
1   1   0   0   0   0   0
2   0   1   0   0   0   0
3   0   0   1   0   0   0
4   0   0   0   1   0   0
5   0   0   0   0   1   0
6   0   0   0   0   0   1

In [ ]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.2,
                                        random_state = 202309)


In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [ ]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3111 sha256=274cf99da284851c8a938775369f6f9bc00104ee277683be59b98546c3a71193
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1870 sha256=c0e44c2d928ae979f6a63dc7106b97047aa5eaf17e8148559d19d5b436b9b5f8
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81843 sha256=930ac155821c914669eaa570ddc9d362e2968b5b4eb29c232f2821458e118398
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce7

In [ ]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 100)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 5)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)


In [ ]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 1 18 20 23 33 44]
 [ 3 11 18 19 33 45]
 [ 1 11 29 33 34 43]
 ...
 [ 4  7 13 26 34 44]
 [ 1 10 20 26 34 45]
 [ 6 11 18 30 39 44]]
DecisionTree :  [[13 19 28 37 38 43]
 [ 3  5  8 19 38 42]
 [13 14 26 33 40 43]
 ...
 [ 4  9 23 33 39 44]
 [ 8 22 35 38 39 41]
 [ 1  4 10 12 28 45]]
RandomForest :  [[ 1 10 13 24 34 45]
 [ 1 11 13 33 34 44]
 [ 1 10 13 24 34 45]
 ...
 [ 1 10 13 24 34 45]
 [ 1 10 13 24 34 45]
 [ 1 11 13 33 34 44]]


In [ ]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

7.965603859976383
9.426488156012988
8.147214992571183


In [ ]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [ ]:
# from xgboost import XGBRegressor

# xmodel = XGBRegressor(random_state = 6,
#                       max_depth = 5,
#                       n_estimators = 200)
# xmodel.fit(Xtr, ytr)

# xpred = xmodel.predict(Xval)
# xpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, xpred)))

In [ ]:
pred = model1.predict(Xtest)
pred

array([[ 1, 11, 13, 26, 39, 45],
       [ 1, 11, 13, 26, 39, 45],
       [ 1, 11, 13, 26, 39, 45],
       [ 1, 11, 13, 26, 39, 45],
       [ 1, 11, 13, 26, 39, 45],
       [ 1, 11, 13, 26, 39, 45]])

In [ ]:
predi = model4.predict(Xtest)
predi

array([[10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41]])

In [ ]:
predo = model5.predict(Xtest)
predo

array([[ 4, 12, 24, 27, 28, 32],
       [ 4, 12, 24, 27, 28, 32],
       [ 4, 12, 24, 27, 28, 32],
       [ 4, 12, 24, 27, 28, 32],
       [ 4, 12, 24, 27, 28, 32],
       [ 4, 12, 24, 27, 28, 32]])