<a href="https://colab.research.google.com/github/YonggunJung/ICT_TensorFlow/blob/main/Pension179%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [51]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/pension.csv')
df

win   pension
0      4687  105948.0
1    105948  858952.0
2    858952  765740.0
3    765740  876021.0
4    876021  803757.0
..      ...       ...
173  754655  124420.0
174  124420  544955.0
175  544955  450558.0
176  450558  162132.0
177  162132       NaN

[178 rows x 2 columns]

In [52]:
Xtrain = df.drop('pension', axis = 1)
Xtrain

win
0      4687
1    105948
2    858952
3    765740
4    876021
..      ...
173  754655
174  124420
175  544955
176  450558
177  162132

[178 rows x 1 columns]

In [53]:
Xtest = np.array(Xtrain.loc[177])
Xtest

array([162132])

In [54]:
Xtrain.drop(177, inplace = True)
Xtrain

win
0      4687
1    105948
2    858952
3    765740
4    876021
..      ...
172  193202
173  754655
174  124420
175  544955
176  450558

[177 rows x 1 columns]

In [55]:
ytrain = df.drop('win', axis = 1)
ytrain

pension
0    105948.0
1    858952.0
2    765740.0
3    876021.0
4    803757.0
..        ...
173  124420.0
174  544955.0
175  450558.0
176  162132.0
177       NaN

[178 rows x 1 columns]

In [56]:
ytrain.dropna(inplace = True)
ytrain

pension
0    105948.0
1    858952.0
2    765740.0
3    876021.0
4    803757.0
..        ...
172  754655.0
173  124420.0
174  544955.0
175  450558.0
176  162132.0

[177 rows x 1 columns]

In [57]:
ytrain =ytrain.astype('int64')
ytrain

pension
0     105948
1     858952
2     765740
3     876021
4     803757
..       ...
172   754655
173   124420
174   544955
175   450558
176   162132

[177 rows x 1 columns]

In [58]:
# from pandas import get_dummies

# Xtrain = pd.get_dummies(Xtrain)
# Xtest = pd.get_dummies(Xtest)
# Xtest

In [59]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.3,
                                        random_state = 202309)


In [60]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [61]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

In [62]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 100)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 5)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
# model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)

model_list1 = [
    ('m1', KNeighborsClassifier()),
    ('m2', LogisticRegression(random_state = 202309)),
    ('m3', SVC(random_state = 202309, probability = True)),
    ('m4', DecisionTreeClassifier(random_state = 202309)),
    ('m5', RandomForestClassifier(random_state = 202309)),
    ('m6', AdaBoostClassifier(random_state = 202309)),
    ('m7', GradientBoostingClassifier(random_state = 202309)),
    ('m8', LGBMClassifier(random_state = 202309))
    # ('m9', XGBClassifier(random_state = 202309, silent = True, verbosity = 0))
]

# 배깅 운영 방식은 위에서 사용한 앙상블, 부스팅들이 사용하고 있다.
# 보팅 운영 방식도 테스트 해보기 위해 사용
# 매개변수 voting은 투표 방식 설정 (hard(다수결)/soft(확률))

model10 = VotingClassifier(estimators=model_list1, voting='hard')

model_list2 = [
    ('m10', KNeighborsClassifier()),
    ('m20', LogisticRegression(random_state = 202309)),
    ('m30', SVC(random_state = 202309, probability = True)),
    ('m40', DecisionTreeClassifier(random_state = 202309)),
    ('m50', RandomForestClassifier(random_state = 202309)),
    ('m60', AdaBoostClassifier(random_state = 202309)),
    ('m70', GradientBoostingClassifier(random_state = 202309)),
    ('m80', LGBMClassifier(random_state = 202309))
    # ('m90', XGBClassifier(random_state = 202309, silent = True, verbosity = 0))
]

model11 = VotingClassifier(estimators=model_list1, voting='soft')

In [63]:
model1.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)

model2.fit(Xtr, ytr)
model3.fit(Xtr, ytr)
model6.fit(Xtr, ytr)
model7.fit(Xtr, ytr)
model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
model10.fit(Xtr, ytr)
model11.fit(Xtr, ytr)


pred1 = model1.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)

pred2 = model2.predict(Xval)
pred3 = model3.predict(Xval)
pred6 = model6.predict(Xval)
pred7 = model7.predict(Xval)
pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
pred10 = model10.predict(Xval)
pred11 = model11.predict(Xval)

print('KNN : ', pred1)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)

# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

In [64]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

print(np.sqrt(mean_squared_error(yval, pred2)))
print(np.sqrt(mean_squared_error(yval, pred3)))
print(np.sqrt(mean_squared_error(yval, pred6)))
print(np.sqrt(mean_squared_error(yval, pred7)))
print(np.sqrt(mean_squared_error(yval, pred8)))
# print(np.sqrt(mean_squared_error(yval, pred9)))
print(np.sqrt(mean_squared_error(yval, pred10)))
print(np.sqrt(mean_squared_error(yval, pred11)))

534354.1368537729
524455.355099989
360338.27853996883
382388.364326694
400578.8389545623
436815.46190434205
400578.8389545623
336186.3526282983
400578.8389545623
400578.8389545623


In [ ]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [ ]:
# from xgboost import XGBRegressor

# xmodel = XGBRegressor(random_state = 6,
#                       max_depth = 5,
#                       n_estimators = 200)
# xmodel.fit(Xtr, ytr)

# xpred = xmodel.predict(Xval)
# xpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, xpred)))

In [65]:
pred = model1.predict(Xtest)
pred

array([2989])

In [67]:
predi = model4.predict(Xtest.reshape(-1, 1))
predi

array([605195])

In [69]:
predo = model5.predict(Xtest.reshape(-1, 1))
predo

array([605195])